sudo: false

language: node_js

branches:
  only:
    - master

notifications:
  email: false

node_js:
  - stable
  - iojs

install:
  - npm install

script:
  - npm run cover

#Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"